#!/bin/bash -eu

ILIBRARIAN_PATH="/usr/share/i-librarian/www"
ILIBRARIAN_CONFIG="${ILIBRARIAN_PATH}/ilibrarian.ini"

rm -f "${ILIBRARIAN_CONFIG}"

echo "[paths]" >> "${ILIBRARIAN_CONFIG}"
echo "library_path = \"/data\"" >> "${ILIBRARIAN_CONFIG}"
echo "temp_path = \"${ILIBRARIAN_TEMP_PATH:-""}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[greeting]" >> "${ILIBRARIAN_CONFIG}"
echo "greeting = \"${ILIBRARIAN_GREETING:-"I, Librarian"}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[openlinks]" >> "${ILIBRARIAN_CONFIG}"
echo "stablelinks = \"${ILIBRARIAN_STABLELINKS:-"0"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "rsslinks = \"${ILIBRARIAN_RSSLINKS:-"0"}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[autosign]" >> "${ILIBRARIAN_CONFIG}"
echo "autosign = \"${ILIBRARIAN_AUTOSIGN:-"0"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "username = \"${ILIBRARIAN_USERNAME:-""}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[reset password]" >> "${ILIBRARIAN_CONFIG}"
echo "reset_password = \"${ILIBRARIAN_RESET_PASSWORD:-"0"}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[fonts and appearance]" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_font_family = \"${ILIBRARIAN_MAIN_WINDOW_FONT_FAMILY:-"Liberation Sans"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_font_size = \"${ILIBRARIAN_MAIN_WINDOW_FONT_SIZE:-"14"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_color = \"${ILIBRARIAN_MAIN_WINDOW_COLOR:-"222222"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_line_height = \"${ILIBRARIAN_MAIN_WINDOW_LINE_HEIGHT:-"1.4"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_link_color = \"${ILIBRARIAN_MAIN_WINDOW_LINK_COLOR:-"404FC3"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_highlight_color = \"${ILIBRARIAN_MAIN_WINDOW_HIGHLIGHT_COLOR:-"FF4500"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_title_font_family = \"${ILIBRARIAN_MAIN_WINDOW_TITLE_FONT_FAMILY:-"Liberation Sans"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_title_font_size = \"${ILIBRARIAN_MAIN_WINDOW_TITLE_FONT_SIZE:-"16"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_abstract_font_family = \"${ILIBRARIAN_MAIN_WINDOW_ABSTRACT_FONT_FAMILY:-"Liberation Sans"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_abstract_font_size = \"${ILIBRARIAN_MAIN_WINDOW_ABSTRACT_FONT_SIZE:-"14"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_abstract_line_height = \"${ILIBRARIAN_MAIN_WINDOW_ABSTRACT_LINE_HEIGHT:-"1.5"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_form_font_family = \"${ILIBRARIAN_MAIN_WINDOW_FORM_FONT_FAMILY:-"Liberation Sans"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_form_font_size = \"${ILIBRARIAN_MAIN_WINDOW_FORM_FONT_SIZE:-"14"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "main_window_background_color = \"${ILIBRARIAN_MAIN_WINDOW_BACKGROUND_COLOR:-"FFFFFF"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "alternating_row_background_color = \"${ILIBRARIAN_ALTERNATING_ROW_BACKGROUND_COLOR:-"F3F3F3"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "top_window_background_color = \"${ILIBRARIAN_TOP_WINDOW_BACKGROUND_COLOR:-"404FC3"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "top_window_color = \"${ILIBRARIAN_TOP_WINDOW_COLOR:-"FFFFFF"}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

echo "[LDAP]" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_active = ${ILIBRARIAN_LDAP_ACTIVE:-false}" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_debug_enabled = ${ILIBRARIAN_LDAP_DEBUG_ENABLED:-false}" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_opt_debug_level = ${ILIBRARIAN_LDAP_OPT_DEBUG_LEVEL:-7}" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_version = ${ILIBRARIAN_LDAP_VERSION:-3}" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_opt_referrals = ${ILIBRARIAN_LDAP_OPT_REFERRALS:-0}" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_server = \"${ILIBRARIAN_LDAP_SERVER:-"ldap://ldap.forumsys.com:389"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_basedn = \"${ILIBRARIAN_LDAP_BASEDN:-"dc=example,dc=com"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_binduser_dn = \"${ILIBRARIAN_LDAP_BINDUSER_DN:-""}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_binduser_pw = \"${ILIBRARIAN_LDAP_BINDUSER_PW:-"password"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_username_attr = \"${ILIBRARIAN_LDAP_USERNAME_ATTR:-"uid"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_userlogin_attr = \"${ILIBRARIAN_LDAP_USERLOGIN_ATTR:-"uid"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_user_rdn = \"${ILIBRARIAN_LDAP_USER_RDN:-""}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_group_rdn = \"${ILIBRARIAN_LDAP_GROUP_RDN:-"ou=groups"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_usergroup_cn = \"${ILIBRARIAN_LDAP_USERGROUP_CN:-""}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_admingroup_cn = \"${ILIBRARIAN_LDAP_ADMINGROUP_CN:-"cn=read-only-admin"}\"" >> "${ILIBRARIAN_CONFIG}"
echo "ldap_filter = \"${ILIBRARIAN_LDAP_FILTER:-"member"}\"" >> "${ILIBRARIAN_CONFIG}"
echo >> "${ILIBRARIAN_CONFIG}"

